### PR TITLE
Update to 64 bit architecture

### PR DESCRIPTION
**Pull request by ezhao1**
Update to 64 bit architecture

### CODE REVIEW

**Comment by christianhelle** [comment]
Thanks! Could I ask you to please remove the .vs, bin, and obj folders. I would prefer to not have binary files in a git repo

**Comment by ezhao1** [comment]
Oh, totally! Sorry about that

**Comment by christianhelle** [comment]
This is awesome! Thanks!

**Comment by christianhelle** [comment]
I haven't really used this in a while but I think I will make a NuGet package out of it or maybe a Xamarin.Forms control in the future

**Comment by ezhao1** [comment]
Yeah, np! This was really helpful for the app im making, so thank you!

**Pull request merged**
